void async_exception_entry();